package:
    type:           yii2-extension
    name:           hipanel-faq
    title:          HiPanel FAQ
    headline:       HiPanel FAQ pages
    keywords:       hipanel, faq
    description:    |
        [![Logo](https://raw.githubusercontent.com/hiqdev/hipanel-core/master/docs/logo.png)](https://hipanel.com/)

        [HiPanel](http://hipanel.com) is next generation control panel for hosting, domains and more.

        This package provides FAQ pages for HiPanel.
